Fix CI clippy
- Upgrade clippy Rust toolchain to 1.88.0, because of:

  ```
  error: rustc 1.87.0 is not supported by the following packages:
    image@0.25.10 requires rustc 1.88.0
    plist@1.9.0 requires rustc 1.88.0
    time@0.3.47 requires rustc 1.88.0
    time-core@0.1.8 requires rustc 1.88.0
    time-core@0.1.8 requires rustc 1.88.0
    time-macros@0.2.27 requires rustc 1.88.0
  ```

- Fix clippy errors.